let selected=null,me=null;const $=x=>document.querySelector(x);
async function api(url,opt={}){const r=await fetch(url,{headers:{"Content-Type":"application/json"},...opt});const d=await r.json();if(!r.ok)throw Error(d.error||"Request failed");return d}
async function load(){me=(await api("/api/me")).user;$("#balance").textContent=`🪙 ৳ ${me?Number(me.balance).toFixed(2):"0.00"}`;const ps=await api("/api/products");$("#products").innerHTML=ps.map(p=>`<article class="card"><div class="banner"><span class="badge">${p.badge}</span><h3>${p.name}</h3></div><h3>${p.name}</h3><p class="desc">${p.description}</p><div class="packs">${p.packages.map(k=>`<div class="pack" onclick="select(${k.id},this)"><strong>${k.name}</strong><em>৳ ${Number(k.price).toFixed(0)}</em></div>`).join("")}</div><button class="buy" onclick="buy()">Buy Now</button></article>`).join("")}
function select(id,el){selected=id;document.querySelectorAll(".pack").forEach(x=>x.style.borderColor="");el.style.borderColor="#19f59a"}
async function buy(){if(!selected)return open("Select a package first.");if(!me)return login();try{const d=await api("/api/orders",{method:"POST",body:JSON.stringify({package_id:selected})});open(`Order #${d.order_id} created successfully.`);load()}catch(e){open(e.message)}}
async function openFund(){if(!me)return login();const s=await api("/api/payment-settings");open(`<h2>Add Fund</h2><p class="desc">Send money manually to the store's selected number, then submit the transaction details. Admin verifies before balance is added.</p><select id="method" onchange="showPayNumber()"><option value="bkash">bKash</option><option value="nagad">Nagad</option><option value="rocket">Rocket</option></select><div id="paynum" class="paynum"></div><input id="amount" type="number" min="1" placeholder="Amount"><input id="sender" placeholder="Your sender number"><input id="trxid" placeholder="Transaction ID"><p class="desc">${s.instructions||"Admin will verify manually."}</p><button class="buy" onclick="submitFund()">Submit Fund Request</button><button class="ghost" onclick="fundHistory()">My Fund Requests</button>`);window.paySettings=s;showPayNumber()}
function showPayNumber(){const m=$("#method").value;const n=window.paySettings?.[m]||"Not set yet";$("#paynum").textContent=`Send to: ${n}`}
async function submitFund(){try{const d=await api("/api/fund-requests",{method:"POST",body:JSON.stringify({method:$("#method").value,amount:Number($("#amount").value),sender_number:$("#sender").value,trxid:$("#trxid").value})});open(d.message)}catch(e){open(e.message)}}
async function fundHistory(){try{const rows=await api("/api/fund-requests");open("<h2>My Fund Requests</h2>"+(rows.length?rows.map(x=>`<p class="desc">#${x.id} — ${x.method} — ৳${x.amount} — ${x.status} — TX: ${x.trxid}</p>`).join(""):"<p>No fund requests yet.</p>"))}catch(e){open(e.message)}}
function login(){open(`<h2>Buyer Login</h2><input id="email" placeholder="Email"><input id="pass" type="password" placeholder="Password"><button class="buy" onclick="doLogin()">Login</button><p class="desc">New buyer? <button class="linkbtn" onclick="register()">Create account</button></p>`) }
async function doLogin(){try{await api("/api/login",{method:"POST",body:JSON.stringify({email:$("#email").value,password:$("#pass").value})});close();load()}catch(e){open(e.message)}}
function register(){open(`<h2>Create Account</h2><input id="name" placeholder="Name"><input id="email" placeholder="Email"><input id="pass" type="password" placeholder="Password (6+ chars)"><button class="buy" onclick="doRegister()">Register</button>`)}
async function doRegister(){try{await api("/api/register",{method:"POST",body:JSON.stringify({name:$("#name").value,email:$("#email").value,password:$("#pass").value})});close();load()}catch(e){open(e.message)}}
async function orders(){if(!me)return login();const os=await api("/api/orders");open("<h2>All Orders</h2>"+(os.length?os.map(o=>`<p class="desc">#${o.id} — ${o.product_name} / ${o.package_name} — ৳${o.amount} — ${o.status}</p>`).join(""):"<p>No orders yet.</p>"))}
function profile(){if(!me)return login();open(`<h2>Profile</h2><p>${me.name||""}<br>${me.email}</p>${me.role==="admin"?`<button class="buy" onclick="location.href='/admin.html'">Open Admin Panel</button>`:""}<button class="buy" onclick="logout()">Logout</button>`)}
async function logout(){await api("/api/logout",{method:"POST"});close();load()}
function support(){open("<h2>Helpline</h2><p class='desc'>Set your support contact in the website when you are ready.</p>")}
function updates(){open("<h2>Updates</h2><p class='desc'>Latest store updates will appear here.</p>")}
function open(html){$("#content").innerHTML=html;$("#modal").classList.add("show")}
function close(){$("#modal").classList.remove("show")}
function closeModal(){close()}
load();
